# Nice Try :) We like you already! But you should really create the docker-compose.yml yourself
# But please create a file called "yay.txt" in your delivered solution, so we know that you found this :)
