version: '2'
services:
  web:
    build: ./Dockerfile.nginx
    environment:
    - NGINX_FASTCGI_PASS=php
    ports:
    - "8080:8080"
    volumes:
    - ./web:/app/web
    links:
    - php
    # Not working on OSX, see below
    # networks:
    #   amazee:
    #     ipv4_address: 192.168.99.100
  php:
    build: ./Dockerfile.php
    # Not working on OSX, see below
    # networks:
    #   amazee:
    #     ipv4_address: 192.168.99.101

# Not working ON OSX as per https://docs.docker.com/docker-for-mac/networking/
#
# Possible workaound:https://github.com/wojas/docker-mac-network
#
# networks:
#   amazee:
#     driver: bridge
#     ipam:
#       config:
#       - subnet: 192.168.99.0/24
#         gateway: 192.168.99.1
